# Generated by Django 2.2.1 on 2019-05-26 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateField(default=datetime.date(2019, 5, 26)),
        ),
    ]
